### ISSUE TITLE
Issue using boost::tuple integration after upgrading from soci 3.2.2 to 3.2.3

### ISSUE THREAD

**Issue by harwinder** [SOCI/soci#429]
I'm facing the following compilation issue after upgrading the SOCI from version 3.2.2 to SOCI 3.2.3. We are using GCC 4.4.7 and boost 1.51.0.

Apologies, I am unable to provide a standalone sample for now, but the following is the code which produces this error:

      soci::rowset< boost::tuple< std::string, std::string, std::string, std::string > >
        rows = ( sql.prepare << sql::GET_CLIENT_DETAILS );

Error details:

```
/home/hss/install/usr/local/include/soci/exchange-traits.h: In instantiation of ‘soci::details::exchange_traits<boost::tuples::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >’:
/home/hss/install/usr/local/include/soci/bind-values.h:183:   instantiated from ‘void soci::details::into_type_vector::exchange_(const soci::details::into_container<T, void>&, ...) [with T = boost::tuples::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>]’
/home/hss/install/usr/local/include/soci/bind-values.h:127:   instantiated from ‘void soci::details::into_type_vector::exchange(const soci::details::into_container<T, Indicator>&) [with T = boost::tuples::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>, Indicator = void]’
/home/hss/install/usr/local/include/soci/statement.h:115:   instantiated from ‘void soci::details::statement_impl::exchange_for_rowset_(const Into&) [with Into = soci::details::into_container<boost::tuples::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>, void>]’
/home/hss/install/usr/local/include/soci/statement.h:71:   instantiated from ‘void soci::details::statement_impl::exchange_for_rowset(const soci::details::into_container<T, Indicator>&) [with T = boost::tuples::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>, Indicator = void]’
/home/hss/install/usr/local/include/soci/statement.h:233:   instantiated from ‘void soci::statement::exchange_for_rowset(const soci::details::into_container<T, Indicator>&) [with T = boost::tuples::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>, Indicator = void]’
/home/hss/install/usr/local/include/soci/rowset.h:125:   instantiated from ‘soci::details::rowset_impl<T>::rowset_impl(const soci::details::prepare_temp_type&) [with T = boost::tuples::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>]’
/home/hss/install/usr/local/include/soci/rowset.h:185:   instantiated from ‘soci::rowset<T>::rowset(const soci::details::prepare_temp_type&) [with T = boost::tuples::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>]’
/code/hss/utrade-code/ccl/cclClientUserMapping.cpp:18:   instantiated from here
/home/hss/install/usr/local/include/soci/exchange-traits.h:34: error: incomplete type ‘soci::details::exchange_traits<boost::tuples::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type> >’ used in nested name specifier
```

The above code works fine with soci 3.2.2. Also, I have the regular includes in place, i.e. I have included `<boost-tuple.h>` before `<soci.h>` and I have defined `SOCI_USE_BOOST` as well without any luck.

Any suggestions/edits would be welcome.

**Comment by snikulov** [comment]
@harwinder have you tried current master branch?

**Comment by mloskot** [comment]
Similar issue has been discussed here
http://stackoverflow.com/questions/9064898/issue-with-rowset-of-boost-tuples-with-soci-c-database-access-library
but it look you have already tried proposed solution.

There was a change between 3.1 and 3.2 in `boost::tuple` specializations and SOCI switched away from hand-rolled specializations, see #186 but that shouldn't break compatibility with Boost 1.5

**Comment by harwinder** [comment]
@snikulov No, but I tried the release 3.2.3 zip.

@mloskot I'm not sure if last time I took the release 3.2.2 zip. However, soci/version.h says the following:

```
#define SOCI_VERSION 300201
#define SOCI_LIB_VERSION "3_2_2"
```

So, at it seems I might have taken the master branch last time, so I'm not sure if this is #186 which is breaking my build.

To further debug the problem, I think I will need to create standalone samples to isolate the problem.

**Comment by harwinder** [comment]
@mloskot I have created a standalone test program: https://gist.github.com/harwinder/7e74e4cbdec4eb892c1e

Works fine with release 3.2.2, but does not compile with release 3.2.3

**Comment by ArnaudD-FR** [comment]
@harwinder to use soci with tuples you have to define macro HAVE_BOOST, without it you can not compile.

I just check on my side on `master` branch and 
`g++ -c testsoci.cpp -o testsoci.o -Isoci4/include` is not working but
`g++ -c testsoci.cpp -o testsoci.o -Isoci4/include -DHAVE_BOOST` can compile

Take care to have build soci with boost support too.

@mloskot does soci has any config file? I mean a file with macro to enable/disable depending on library build configuration? Any soci header should include it instead of defining this kind of macro by hand.

**Comment by mloskot** [comment]
@harwinder There is an issue indeed. Between 3.2.2 and 3.2.3, role of `HAVE_BOOST` has changed and it disconnected from `SOCI_USE_BOOST` legacy.

In SOCI 3.2.3 (and current master too) `HAVE_BOOST` controls the Boost support in SOCI.
The `SOCI_USE_BOOST` is still dangling in the all-in-one header `soci.h` and in fact, it should be automatically defined if `HAVE_BOOST` is defined - that is missing, unfortunately.

That is, safest bet is to define both of the preprocessor definitions in SOCI client build configuration.

@ArnaudD-FR No, it does not, unfortunately. I've failed to wrap my head around [CMake project config files to provide more complete packaging](https://cmake.org/cmake/help/git-master/manual/cmake-packages.7.html). That would mean more coupling with CMake though. So, it may be better to just provide such generate header with `HAVE_*`-kind of macros for each enabled feature/dependency.

**Comment by ArnaudD-FR** [comment]
@mloskot it could be fine to add CMake project config file support, it will be easier to import SOCI in other CMake projects.

But for any non CMake project we should still be independent of CMake, that why I recommend to use some kind of soci_config.h that will include all required definitions, based on cmake [configure_file](https://cmake.org/cmake/help/git-master/command/configure_file.html?highlight=configure)

**Comment by harwinder** [comment]
@mloskot @ArnaudD-FR Thanks for your reply and help. HAVE_BOOST macro fixes the tuple issue.

**Comment by mloskot** [comment]
@ArnaudD-FR Yes, I agree it should be solved at soruce level, in a way agnostic to CMake or any build configuration.

@harwinder Glad to hear. Closing.
