### ISSUE TITLE
soci/soci-platform.h(47) conflict with boost/system/detail/system_category_win32.hpp(52)

### ISSUE THREAD

**Issue by sinall** [SOCI/soci#714]
I met error when upgrading boost to 1.69.0:
> 1>d:\.conan\9b4b5d\1\include\boost\system\detail\system_category_win32.hpp(52): error C2039: '_snprintf': is not a member of 'std'
> 1>  d:\.conan\9b4b5d\1\include\boost\move\detail\iterator_traits.hpp(29): note: see declaration of 'std'
> 

<system_category_win32.hpp> is a new file introduced in boost-system-1.69.0. It is included in <boost/system/error_code.hpp>.

VC2015 has snprintf in <cstdio>, so could it be changed to below?
```
// Define if you have the snprintf variants.
#if _MSC_VER < 1900
#define snprintf _snprintf
#endif

```

Workaround:
```
#include <soci/soci.h>
#undef snprintf
```

The <soci/soci.h> includes "soci/soci-platform.h", so those definitions impact a lot of source files.

**Comment by myd7349** [comment]
Hi! @sinall I think this issue has been fixed in #717 .

**Comment by mloskot** [comment]
Yes, it's been fixed.
